server/clients/coingecko/client.go, server/config/config.go, server/cron/cron.go, server/exmaple.yaml, server/go.mod, server/go.sum, server/handler/multisig.go, server/handler/price.go, server/schema/price_info.go, server/schema/schema.sql, server/server.go, server/utils/logger.go, src/features/common/commonService.ts, src/features/common/commonSlice.js, src/pages/Overview.js
=> feat: show USD value

frontend/src/pages/Home.js, frontend/src/pages/gov/Proposal.js, frontend/src/pages/gov/ProposalInfo.js
changed ProposalInfo component according to new staking slice
=> fix: fix proposalInfo

.gitignore, frontend/src/features/common/commonService.ts, frontend/src/features/common/commonSlice.js, frontend/src/pages/Home.js, frontend/src/pages/OverviewPage.jsx, frontend/src/pages/general-overview/ChainDetails.js, frontend/src/pages/general-overview/GeneralOverview.js, frontend/src/pages/stakingOverview/StakingOverview.js, server/logs.txt
=> feat: add overview page

frontend/src/pages/general-overview/ChainDetails.js, frontend/src/pages/general-overview/GeneralOverview.js
- fixed balance issue
- replaced chainId with chain name
- made UI changes
=> fix: fixed Balance issue and network name 

frontend/src/pages/OverviewPage.jsx, frontend/src/pages/general-overview/ChainDetails.js, frontend/src/pages/general-overview/GeneralOverview.js
- Add loader
- Fix UI issues
ref: #498
=> fix: overview page UI fixes

frontend/src/pages/general-overview/ChainDetails.js, frontend/src/pages/general-overview/GeneralOverview.js
- added link to chan-specific overview page
- refactored way to get chain name from chain id
=> refactor : added overview link

frontend/src/components/group/GroupCard.tsx, frontend/src/components/group/GroupList.tsx, frontend/src/components/group/MembersTable.js, frontend/src/components/group/PolicyCard.jsx, frontend/src/components/group/PolicyDetails.tsx, frontend/src/components/group/PolicyForm.jsx, frontend/src/components/group/ProposalCard.tsx, frontend/src/components/group/bulk/Delegate.jsx, frontend/src/components/group/bulk/RedelegateForm.jsx, frontend/src/components/group/bulk/UnDelegateForm.jsx, frontend/src/features/group/groupSlice.js, frontend/src/pages/GroupPage.jsx, frontend/src/pages/Home.js, frontend/src/pages/OverviewPage.jsx, frontend/src/pages/group/ActiveProposals.jsx, frontend/src/pages/group/AddManualTx.jsx, frontend/src/pages/group/AdminGroupList.jsx, frontend/src/pages/group/CreateGroup.jsx, frontend/src/pages/group/CreateGroupInfoForm.jsx, frontend/src/pages/group/CreateGroupMembersForm.jsx, frontend/src/pages/group/CreateGroupPolicy.js, frontend/src/pages/group/CreateProposal.jsx, frontend/src/pages/group/Group.jsx, frontend/src/pages/group/GroupInfo.jsx, frontend/src/pages/group/MemberGroupList.jsx, frontend/src/pages/group/Policy.jsx, frontend/src/pages/group/PolicyInfo.jsx, frontend/src/pages/group/PolicyProposalsList.jsx, frontend/src/pages/group/Proposal.jsx, frontend/src/pages/group/UpdateGroupInfoDialog.jsx
=> refactor: migrate group page

frontend/src/components/ActiveValidators.jsx, frontend/src/components/InActiveValidators.jsx, frontend/src/pages/StakingPage.jsx, frontend/src/pages/stakingOverview/Chain.js, frontend/src/pages/stakingOverview/StakingOverview.js, frontend/src/pages/stakingOverview/StakingTotal.js, frontend/src/pages/stakingOverview/Validators.js
- Remove unnecessary chains selection menu in staking overview page.
- Add chain specific page navigation.
- Remove pagination from validators page.
=> refactor: remove validators pagination

frontend/src/components/group/PolicyCard.jsx, frontend/src/pages/group/Group.jsx, frontend/src/pages/slashing/UnjailPage.jsx
=> refactor: update group polices list

frontend/src/components/group/PolicyDetails.tsx, frontend/src/components/group/ProposalCard.tsx, frontend/src/pages/group/PolicyInfo.jsx, frontend/src/pages/group/PolicyProposalsList.jsx, frontend/src/utils/datetime.js
=> refactor: update group policy details page

frontend/src/components/group/PolicyCard.jsx, frontend/src/components/group/PolicyDetails.tsx, frontend/src/pages/group/CreateGroup.jsx, frontend/src/pages/group/CreateGroupPolicy.js, frontend/src/pages/group/PolicyInfo.jsx
- Fixed incorrect voting period and execution delay 
- Fixed decision policy type ui issue in create group
=> fix: group fixes

frontend/chains/simapp.json, frontend/src/components/common/SelectNetwork.jsx, frontend/src/features/common/commonSlice.js, frontend/src/pages/Dashboard.js, frontend/src/utils/chainsInfo.ts
=> fix: fix transaction status endpoint

frontend/src/components/CustomAppBar.js
=> navbar: hide authz mode button if wallet is not connected

frontend/src/components/ConnectWallet.jsx, frontend/src/components/CustomAppBar.js, frontend/src/features/distribution/distributionSlice.js, frontend/src/pages/overview/chain/Assets.js, frontend/src/pages/overview/chain/Overview.js, frontend/src/pages/overview/overview/ChainDetails.js
- Changed assets table ui
- Add connect wallet button
=> refactor: Overview page ui changes

frontend/src/features/bank/bankSlice.js, frontend/src/pages/MultiTx.jsx
- Add loader to submit transaction button
- Reset list of Txns after transaction is completed
=> chore: multiTx ui/ux changes

frontend/src/pages/overview/chain/Assets.js, frontend/src/pages/overview/overview/ChainDetails.js, frontend/src/pages/overview/overview/ChainsOverview.js
=> ui: overview page ui changes

frontend/src/pages/Dashboard.js, frontend/src/pages/staking/overview/AuthzDelegations.js, frontend/src/pages/staking/overview/StakingGranter.js, frontend/src/utils/authorizations.ts
- changed loading UI when authz claim
- fixed staking tab panel in authz mode
=> refactor: authz staking page changes

frontend/src/components/CustomAppBar.js, frontend/src/components/DialogSelectNetwork.jsx, frontend/src/components/common/SelectNetwork.jsx, frontend/src/features/common/commonSlice.js, frontend/src/pages/Dashboard.js
- Added select network pop up
- Also fixed tx status endpoint issue
=> feat: add select network pop up

frontend/src/pages/overview/overview/ChainsOverview.js, frontend/src/utils/chainsInfo.ts
- sort by balance -> sort by all assets (balance, staked, rewards)
- fixed Overview page mismatched fields
=> refactor: refactored overview page

frontend/src/components/group/bulk/RedelegateForm.jsx, frontend/src/components/group/bulk/UnDelegateForm.jsx, frontend/src/components/multisig/bulk/Delegate.jsx, frontend/src/components/multisig/bulk/RedelegateForm.jsx, frontend/src/components/multisig/bulk/UnDelegateForm.jsx, frontend/src/pages/multisig/tx/PageCreateTx.jsx, frontend/src/pages/multisig/tx/PageMultisigInfo.js
- Fix delegate, redelegate, undelegate tnxs
- Fix staked amount
=> fix: fix create transaction in multisig 

frontend/src/pages/overview/overview/ChainDetails.js
=> ui: remove IBC badge in general overview page

frontend/src/components/Vote.js
=> gov: Add close icon to vote dialog

frontend/chains/agoric.json, frontend/chains/desmos.json, frontend/chains/omniflixhub.json, frontend/chains/quicksilver.json, frontend/chains/tgrade.json, frontend/src/utils/chainsInfo.ts
Added below networks config
- Agoric
- Tgrade
- Quicksilver
- Desmos
- OmniflixHub
=> Add network configurations

frontend/src/components/DialogDeposit.jsx, frontend/src/features/gov/govService.ts, frontend/src/features/gov/govSlice.js, frontend/src/pages/Home.js, frontend/src/pages/gov/ProposalsPage.jsx, frontend/src/pages/gov/chain/ProposalInfo.js, frontend/src/pages/gov/chain/ProposalItem.js, frontend/src/pages/gov/chain/Proposals.js
- Added required deposit amount
- Added drop down for chain specific gov proposals
=> gov: gov ui changes

frontend/src/pages/overview/overview/ChainsOverview.js
=> fix: fix overview incorrect rewards

frontend/src/pages/gov/chain/ProposalInfo.js
=> fix: fix gov proposal incorrect voting data

frontend/src/pages/Home.js
=> fix: fix active tab indication issue

frontend/src/pages/Home.js, frontend/src/utils/authorizations.ts
=> fix: fix authz mode incorrect active tabs

frontend/src/pages/overview/overview/ChainsOverview.js, frontend/src/utils/util.js
=> overview: Add total wallet balance

frontend/src/features/distribution/distributionSlice.js, frontend/src/pages/overview/chain/Assets.js, frontend/src/pages/overview/overview/ChainDetails.js, frontend/src/pages/overview/overview/ChainsOverview.js
- Fix multiple requests to rewards api
- Added IBC tokens usd value field
=> fix: fix multiple requests to rewards api

frontend/src/components/AuthorizationInfo.js, frontend/src/utils/authorizations.ts
=> feat: handle staking authz

frontend/src/pages/overview/overview/ChainsOverview.js
=> fix: remove value field from native tokens table

frontend/chains/passage.json, frontend/src/components/DialogDeposit.jsx, frontend/src/utils/chainsInfo.ts
- Fixed passage rest endpoint
- Displayed coin denom in deposit dialog
=> fix: fix passage rest endpoint

frontend/src/utils/chainDenoms.json
Added assets info for following networks
- Agoric
- Tgrade
- Desmos
- OmniflixHub
- QuickSilver
=> feat: add asset info

frontend/src/features/airdrop/airdropService.js, frontend/src/features/auth/service.ts, frontend/src/features/authz/service.ts, frontend/src/features/bank/service.ts, frontend/src/features/common/commonService.ts, frontend/src/features/distribution/service.ts, frontend/src/features/feegrant/feegrantService.js, frontend/src/features/gov/govService.ts, frontend/src/features/group/groupService.js, frontend/src/features/multisig/multisigService.js, frontend/src/features/node/nodeService.js, frontend/src/features/staking/stakingService.ts, frontend/src/features/utils.js, frontend/src/pages/SendPage.jsx, frontend/src/pages/feegrant/NewFeegrant.js, frontend/src/pages/overview/chain/Overview.js, frontend/src/pages/overview/overview/ChainsOverview.js, frontend/src/pages/staking/chain/Validators.js, frontend/src/pages/staking/overview/StakingGranter.js, frontend/src/pages/staking/overview/StakingGrants.js
- Added util function to get valid URL
=> feat: Add url validation

frontend/src/features/staking/stakeSlice.js, frontend/src/pages/staking/chain/Validators.js
Staking action buttons are getting display before validator info is fetched from api. So, when clicked on delegate validator address is going empty.
Added a loader to wait for validators info.
=> staking: add loader in chain specific staking page

frontend/src/pages/gov/ProposalsPage.jsx, frontend/src/pages/gov/chain/Proposals.js
When switching between networks, Chain specific gov page is showing same proposal for all chains
=> fix: fix chain specific gov page

frontend/src/components/multisig/bulk/UnDelegateForm.jsx, frontend/src/pages/multisig/tx/PageCreateTx.jsx
- fix: Page is broken when tried to add delegate transaction in multisig
- fix: Page is broken selecting undelegate transaction after refreshing page in multisig
=> fix: fix add delegate txn in multisig

frontend/src/components/ConnectWalletButton.tsx, frontend/src/components/TopNav.tsx, frontend/src/services/walletService.ts, frontend/src/utils/localStorage.ts
- wallet connection is integrated with local storage so that every reload doesn't have to display landing page (connect Wallet Page)
=> refactor: connect wallet nuances

frontend/src/store/features/common/commonService.ts, frontend/src/store/features/common/commonSlice.ts, frontend/src/store/store.ts, frontend/src/types/common.d.ts
=> feat: Add common slice and common service

frontend/src/utils/networkConfigSchema.json
=> fix: fix add network config format

frontend/src/app/(routes)/multisig/components/common/SignTxn.tsx, frontend/src/app/(routes)/multisig/utils/multisigSigning.ts, frontend/src/store/features/multisig/multisigService.ts, frontend/src/store/features/multisig/multisigSlice.ts
- Add try with another RPC url to handle inactive APIs
=> chore: add multiple RPCs for signing client

frontend/src/app/(routes)/settings/authz/new-authz/components/NewAuthzPage.tsx, frontend/src/app/(routes)/settings/components/NetworksList.tsx, frontend/src/app/(routes)/settings/feegrant/components/FeegrantsByMe.tsx, frontend/src/app/(routes)/settings/feegrant/components/FeegrantsToMe.tsx, frontend/src/app/(routes)/settings/feegrant/new-feegrant/components/NewFeegrantPage.tsx, frontend/src/components/main-layout/ProfileDialog.tsx, frontend/src/utils/constants.ts
- Disable authz and feegrant creation based on chain config
- Group all feegrant by granter address
- Turn off feegrant and authz mode on logout
=> chore: authz and feegrant updates
